version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/api:/app
      - /app/node_modules
    restart: unless-stopped

  ui:
    build:
      context: ./examples/ui
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3000
    depends_on:
      - api
    volumes:
      - ./examples/ui:/app
      - /app/node_modules
    restart: unless-stopped 