name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          fi
          if [ -d "src/api" ] && [ -f "src/api/package.json" ]; then
            cd src/api && npm ci
          fi
          if [ -d "examples/ui" ] && [ -f "examples/ui/package.json" ]; then
            cd examples/ui && npm ci
          fi
      - name: Run linters
        run: |
          if [ -f "package.json" ] && grep -q "lint" package.json; then
            npm run lint
          fi
          if [ -d "src/api" ] && [ -f "src/api/package.json" ] && grep -q "lint" src/api/package.json; then
            cd src/api && npm run lint
          fi
          if [ -d "examples/ui" ] && [ -f "examples/ui/package.json" ] && grep -q "lint" examples/ui/package.json; then
            cd examples/ui && npm run lint
          fi

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          fi
          if [ -d "src/api" ] && [ -f "src/api/package.json" ]; then
            cd src/api && npm ci
          fi
          if [ -d "examples/ui" ] && [ -f "examples/ui/package.json" ]; then
            cd examples/ui && npm ci
          fi
      - name: Run tests
        run: |
          if [ -f "package.json" ] && grep -q "test" package.json; then
            npm test
          fi
          if [ -d "src/api" ] && [ -f "src/api/package.json" ] && grep -q "test" src/api/package.json; then
            cd src/api && npm test
          fi
          if [ -d "examples/ui" ] && [ -f "examples/ui/package.json" ] && grep -q "test" examples/ui/package.json; then
            cd examples/ui && npm test
          fi 