name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd examples/ui
          npm install
      
      - name: Build static site
        run: |
          cd examples/ui
          # Create a simple index.html if the build fails
          if ! npm run build; then
            mkdir -p dist
            echo "<html><head><title>GitHub Demo UI</title></head><body><h1>GitHub Demo Repository</h1><p>This is a placeholder page. The actual UI build failed.</p><p>Please check the GitHub Actions logs for details.</p></body></html>" > dist/index.html
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './examples/ui/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 